version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=appointments
      - JWT_SECRET=change_this_to_a_secure_secret_in_production
      - NODE_ENV=production
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appointments
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  