version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgresP@s1
      - DATABASE_NAME=appointments
      - JWT_SECRET=change_this_to_a_secure_secret_in_production
      - NODE_ENV=production
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    ports:
      - "0.0.0.0:54322:5432"
    environment:
      - POSTGRES_PASSWORD=postgresP@s1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appointments
      - POSTGRES_HOST_AUTH_METHOD=md5
    command: 
      - "postgres"
      - "-c"
      - "listen_addresses=*"      
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  